steps:
    - name: gcr.io/cloud-builders/docker
      args:
        - build
        - '--no-cache'
        - '-t'
        - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
        - un-autre-geek/app
        - '-f'
        - un-autre-geek/app/Dockerfile
      id: Build
    - name: gcr.io/cloud-builders/docker
      args:
        - push
        - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      id: Push
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk
      args:
        - run
        - services
        - update
        - $_SERVICE_NAME
        - '--platform=managed'
        - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
        - >-
          --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
        - '--region=$_DEPLOY_REGION'
        - '--quiet'
      id: Deploy
      entrypoint: gcloud
  images:
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  options:
    substitutionOption: ALLOW_LOOSE
  substitutions:
    _DEPLOY_REGION: northamerica-northeast1
    _LABELS: gcb-trigger-id=a20355dc-ecb0-4d78-a3da-7bb48b4bf8b6
    _TRIGGER_ID: a20355dc-ecb0-4d78-a3da-7bb48b4bf8b6
    _GCR_HOSTNAME: us.gcr.io
    _PLATFORM: managed
    _SERVICE_NAME: app
  tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - app
  timeout:  1200s